# Base image
FROM node:20

# Set working directory inside container
WORKDIR /usr/src/app

# Copy package.json first
COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy entire source code
COPY . .

# Expose NestJS default port
EXPOSE 3000

# Start the dev server (watch mode)
CMD ["npm", "run", "start:dev"]
