version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: urban_tasker_app
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src:/usr/src/app/src

  mongo:
    image: mongo:7.0
    container_name: mongodb
    command: ['--port', '27019']
    ports:
      - '27019:27019'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    container_name: redis_server
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  mongo_data:
    driver: local
  cache:
    driver: local
