include:
  - infra.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urban_tasker_app
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/var/log/app
      - ~/.aws:/root/.aws:ro
