export const CHAT_TOKEN = {
  CHAT_SERVICE: Symbol('CHAT_SERVICE'),
  CHAT_REPOSITORY: Symbol('CHAT_REPOSITORY'),

  MESSAGE_SERVICE: Symbol('MESSAGE_SERVICE'),
  MESSAGE_REPOSITORY: Symbol('MESSAGE_REPOSITORY'),
};
