export const USER_TOKENS = {
  REPOSITORY: Symbol('USER_REPOSITORY'),
  SERVICE: Symbol('USER_SERVICE'),
  PROFILE_SERVICE: Symbol('USER_PROFILE_SERVICE'),
  ADMIN_USER_SERVICE: Symbol('ADMIN_USER_SERVICE'),
};
