export const WALLET_TOKENS = {
  WALLET_REPOSITORY: Symbol('WALLET_REPOSITORY'),
  WALLET_SERVICE: Symbol('WALLET_SERVICE'),
  WALLET_TRANSACTION_REPOSITORY: Symbol('WALLET_TRANSACTION_REPOSITORY'),
  WALLET_TRANSACTION_SERVICE: Symbol('WALLET_TRANSACTION_SERVICE'),
};
