export const AUTH_TOKENS = {
  AUTH_SERVICE: Symbol('AUTH_SERVICE'),
  SIGNUP_SERVICE: Symbol('SIGNUP_SERVICE'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
  REFERESH_TOKEN_SERVICE: Symbol('REFERESH_TOKEN_SERVICE'),
  PASSWORD_SERVICE: Symbol('PASSWORD_SERVICE'),

  REFERESH_TOKEN_REPOSITORY: Symbol('REFERESH_TOKEN_REPOSITORY'),
};
