export const AUTH_TOKENS = {
  AUTH_SERVICE: Symbol('AUTH_SERVICE'),
  SOCKET_AUTH_SERVICE: Symbol('SOCKET_AUTH_SERVICE'),
  SIGNUP_SERVICE: Symbol('SIGNUP_SERVICE'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
  PASSWORD_SERVICE: Symbol('PASSWORD_SERVICE'),
};
