export const TASKER_TOKEN = {
  SERVICE: Symbol('TASKER_SERVICE'),
  REPOSITORY: Symbol('TASKER_REPOSITORY'),

  PORTFOLIO_SERVICE: Symbol('PORTFOLIO_SERVICE'),
  PORTFOLIO_REPOSITORY: Symbol('PORTFOLIO_REPOSITORY'),
};
