export const CATEGORY_TOKEN = {
  CATEGORY_REPOSITORY: Symbol('CATEGORY-REPOSITORY'),
  SUBCATEGORY_REPOSITORY: Symbol('SUBCATEGORY-REPOSITORY'),
  //services
  CATEGORY_SERVICE: Symbol('CATEGORY_SERVICE'),
  SUBCATEGORY_SERVICE: Symbol('SUBCATEGORY_SERVICE'),
};
