export const COMPLIANTS_TOKENS = {
  COMPLIANTS_SERVICE: Symbol('COMPLIANTS_SERVICE'),
  ADMIN_COMPLIANTS_SERVICE: Symbol('ADMIN_COMPLIANTS_SERVICE'),
  COMPLIANTS_REPOSITORY: Symbol('COMPLIANTS_REPOSITORY'),
};
