export const BOOKING_TOKEN = {
  BOOKING_REPOSITORY: Symbol('BOOKING-REPOSITORY'),
  //services
  BOOKING_SERVICE: Symbol('BOOKING_SERVICE'),
  TASKERS_BOOKING_SERVICE: Symbol('TASKERS_BOOKING_SERVICE'),
  TASKERS_BOOKING_REPORT_SERVICE: Symbol('TASKERS_BOOKING_REPORT_SERVICE'),
  ADMIN_BOOKING_SERVICE: Symbol('ADMIN_BOOKING_SERVICE'),
};
